### ISSUE TITLE
Yahoo decided to screw up the API. Replacement code here.

### ISSUE THREAD

**Issue by marcushouse** [someoneandsons/craft-currency#1]
Switch out getConversion function code within CurrencyService for the following (exact same cache result and arguments, just use a different service from http://api.fixer.io/.
[CurrencyService.php.txt](https://github.com/someoneandsons/craft-currency/files/1436039/CurrencyService.php.txt)

**Comment by monachilada** [comment]
This is great, thanks so much for pointing it out and suggesting a fix. I cleaned it up a bit, sticking with the Guzzle library for grabbing the API response and making the case of a a conversion to the same currency a little more elegant. Thanks again!
