### ISSUE TITLE
Update plugin due to API changes

### ISSUE THREAD

**Issue by mark-adigital** [someoneandsons/craft-currency#3]
Hi,

Last week we had a site go down briefly due to the endpoint provided by fixer being updated and a new requirement that users of the API create an account.

In the short term I've patched this by updating `services/CurrencyService.php` with the following edits to lines 18 and 19:

`$url = '/latest?base='.$from.'&symbols='.$to.'&access_key=ACCESS_KEY';
$client = new \Guzzle\Http\Client('http://data.fixer.io/api');`

For the moment I've hardcoded the access key, but it would obviously be more useful if this could be a plugin setting. It might also be worth having an additional setting to specify `https` or not as  the secure endpoint is now only available with a paid plan.

If these updates could be made and released that would be great.

Thanks,

Mark

**Comment by monachilada** [comment]
I'm not really supporting this plugin anymore as none of my sites are using it any longer. It should really be updated for Craft 3 anyway. I'd be happy to review and merge a pull request if you made the suggested changes.

**Comment by monachilada** [comment]
Merged #4 and updated the README to reflect the new changes.
